<?php

namespace Database\Seeders;

use App\Models\Game;
use App\Models\Jackpot;
use App\Models\LiveCommunityWin;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Create Admin Account
        $admin = User::firstOrCreate(
            ['email' => 'admin@royalplay.social'],
            [
                'name' => 'RoyalPlay Admin',
                'user_code' => 'admin_1',
                'game_balance' => 10000.00,
                'rtp' => 95,
                'avatar' => 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
                'vip_level' => 10,
                'vip_points' => 15000,
                'is_admin' => true,
                'password' => Hash::make('admin123'),
            ]
        );

        // 2. Grand Progressive Jackpot
        Jackpot::firstOrCreate(
            ['name' => 'Grand Progressive Jackpot'],
            [
                'current_pool' => 54890.45,
                'base_pool' => 20000.00,
                'cut_percentage' => 0.0050,
                'last_winner_name' => 'Viktor K.',
                'last_win_amount' => 18450.80,
                'last_won_at' => now()->subDays(2),
            ]
        );

        // 3. Populate Casino Games Catalog
        $gamesData = [
            // Pragmatic Play
            [
                'provider_code' => 'PRAGMATIC',
                'game_code' => 'vs20olympgate',
                'name' => 'Gates of Olympus 1000',
                'slug' => 'gates-of-olympus-1000',
                'cover_image' => 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
                'category' => 'popular',
                'is_featured' => true,
                'rtp_display' => '96.50%',
                'volatility' => 'Very High',
                'min_bet' => 0.20,
                'max_bet' => 100.00,
                'max_multiplier' => 15000,
                'play_count' => 1420,
                'tags' => ['Hot', 'Bonus Buy', 'Multiplier'],
            ],
            [
                'provider_code' => 'PRAGMATIC',
                'game_code' => 'vs20sweetbonz',
                'name' => 'Sweet Bonanza 1000',
                'slug' => 'sweet-bonanza-1000',
                'cover_image' => 'https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?w=600&auto=format&fit=crop&q=80',
                'category' => 'popular',
                'is_featured' => true,
                'rtp_display' => '96.53%',
                'volatility' => 'High',
                'min_bet' => 0.20,
                'max_bet' => 125.00,
                'max_multiplier' => 25000,
                'play_count' => 1280,
                'tags' => ['Hot', 'Tumble', 'Free Spins'],
            ],
            [
                'provider_code' => 'PRAGMATIC',
                'game_code' => 'vs20sugarush',
                'name' => 'Sugar Rush 1000',
                'slug' => 'sugar-rush-1000',
                'cover_image' => 'https://images.unsplash.com/photo-1534432182912-63863115e106?w=600&auto=format&fit=crop&q=80',
                'category' => 'slots',
                'is_featured' => true,
                'rtp_display' => '96.50%',
                'volatility' => 'Very High',
                'min_bet' => 0.20,
                'max_bet' => 100.00,
                'max_multiplier' => 25000,
                'play_count' => 950,
                'tags' => ['Bonus Buy', 'Sticky Multipliers'],
            ],
            [
                'provider_code' => 'PRAGMATIC',
                'game_code' => 'vs20doghouse',
                'name' => 'The Dog House Megaways',
                'slug' => 'the-dog-house-megaways',
                'cover_image' => 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&auto=format&fit=crop&q=80',
                'category' => 'megaways',
                'is_featured' => false,
                'rtp_display' => '96.55%',
                'volatility' => 'Very High',
                'min_bet' => 0.20,
                'max_bet' => 100.00,
                'max_multiplier' => 12305,
                'play_count' => 840,
                'tags' => ['Megaways', 'Sticky Wilds'],
            ],
            [
                'provider_code' => 'PRAGMATIC',
                'game_code' => 'vs10bbhasplash',
                'name' => 'Big Bass Splash',
                'slug' => 'big-bass-splash',
                'cover_image' => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&auto=format&fit=crop&q=80',
                'category' => 'slots',
                'is_featured' => true,
                'rtp_display' => '96.71%',
                'volatility' => 'High',
                'min_bet' => 0.10,
                'max_bet' => 250.00,
                'max_multiplier' => 5000,
                'play_count' => 1100,
                'tags' => ['Fisherman', 'Collect Feature'],
            ],
            [
                'provider_code' => 'PRAGMATIC',
                'game_code' => 'vs20starlight',
                'name' => 'Starlight Princess 1000',
                'slug' => 'starlight-princess-1000',
                'cover_image' => 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80',
                'category' => 'popular',
                'is_featured' => false,
                'rtp_display' => '96.50%',
                'volatility' => 'Very High',
                'min_bet' => 0.20,
                'max_bet' => 100.00,
                'max_multiplier' => 15000,
                'play_count' => 790,
                'tags' => ['Anime', 'Multiplier'],
            ],

            // PG Soft
            [
                'provider_code' => 'PGSOFT',
                'game_code' => 'mahjong-ways-2',
                'name' => 'Mahjong Ways 2',
                'slug' => 'mahjong-ways-2',
                'cover_image' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
                'category' => 'popular',
                'is_featured' => true,
                'rtp_display' => '96.95%',
                'volatility' => 'Medium',
                'min_bet' => 0.20,
                'max_bet' => 50.00,
                'max_multiplier' => 100000,
                'play_count' => 1520,
                'tags' => ['Asian', 'Gold Plated Symbols'],
            ],
            [
                'provider_code' => 'PGSOFT',
                'game_code' => 'fortune-tiger',
                'name' => 'Fortune Tiger',
                'slug' => 'fortune-tiger',
                'cover_image' => 'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?w=600&auto=format&fit=crop&q=80',
                'category' => 'slots',
                'is_featured' => false,
                'rtp_display' => '96.81%',
                'volatility' => 'Medium',
                'min_bet' => 0.25,
                'max_bet' => 75.00,
                'max_multiplier' => 2500,
                'play_count' => 880,
                'tags' => ['Respin Feature', '10x Multiplier'],
            ],
            [
                'provider_code' => 'PGSOFT',
                'game_code' => 'fortune-rabbit',
                'name' => 'Fortune Rabbit',
                'slug' => 'fortune-rabbit',
                'cover_image' => 'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=600&auto=format&fit=crop&q=80',
                'category' => 'slots',
                'is_featured' => false,
                'rtp_display' => '96.75%',
                'volatility' => 'Medium',
                'min_bet' => 0.20,
                'max_bet' => 50.00,
                'max_multiplier' => 5000,
                'play_count' => 640,
                'tags' => ['Prize Symbols', 'Fortune Spins'],
            ],

            // Hacksaw Gaming
            [
                'provider_code' => 'HACKSAW',
                'game_code' => 'wanted-dead-or-a-wild',
                'name' => 'Wanted Dead or a Wild',
                'slug' => 'wanted-dead-or-a-wild',
                'cover_image' => 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
                'category' => 'buy_feature',
                'is_featured' => true,
                'rtp_display' => '96.38%',
                'volatility' => 'Extreme',
                'min_bet' => 0.20,
                'max_bet' => 100.00,
                'max_multiplier' => 12500,
                'play_count' => 1340,
                'tags' => ['VS Duel', 'Dead Mans Hand'],
            ],
            [
                'provider_code' => 'HACKSAW',
                'game_code' => 'rip-city',
                'name' => 'RIP City',
                'slug' => 'rip-city',
                'cover_image' => 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600&auto=format&fit=crop&q=80',
                'category' => 'slots',
                'is_featured' => false,
                'rtp_display' => '96.22%',
                'volatility' => 'Medium-High',
                'min_bet' => 0.10,
                'max_bet' => 100.00,
                'max_multiplier' => 12500,
                'play_count' => 720,
                'tags' => ['Expanding Wilds', 'Ro$s Bonus'],
            ],
            [
                'provider_code' => 'HACKSAW',
                'game_code' => 'chaos-crew-2',
                'name' => 'Chaos Crew 2',
                'slug' => 'chaos-crew-2',
                'cover_image' => 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
                'category' => 'buy_feature',
                'is_featured' => false,
                'rtp_display' => '96.27%',
                'volatility' => 'High',
                'min_bet' => 0.10,
                'max_bet' => 100.00,
                'max_multiplier' => 20000,
                'play_count' => 690,
                'tags' => ['Cranky Cat', 'Super Bonus'],
            ],

            // Amusnet
            [
                'provider_code' => 'AMUSNET',
                'game_code' => 'shining-crown',
                'name' => 'Shining Crown',
                'slug' => 'shining-crown',
                'cover_image' => 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&auto=format&fit=crop&q=80',
                'category' => 'jackpots',
                'is_featured' => true,
                'rtp_display' => '96.37%',
                'volatility' => 'Low-Medium',
                'min_bet' => 0.20,
                'max_bet' => 200.00,
                'max_multiplier' => 5000,
                'play_count' => 990,
                'tags' => ['Classic Fruit', 'Jackpot Cards'],
            ],
            [
                'provider_code' => 'AMUSNET',
                'game_code' => '20-super-hot',
                'name' => '20 Super Hot',
                'slug' => '20-super-hot',
                'cover_image' => 'https://images.unsplash.com/photo-1528825871115-3581a5387919?w=600&auto=format&fit=crop&q=80',
                'category' => 'slots',
                'is_featured' => false,
                'rtp_display' => '95.79%',
                'volatility' => 'Low',
                'min_bet' => 0.20,
                'max_bet' => 200.00,
                'max_multiplier' => 1000,
                'play_count' => 610,
                'tags' => ['Retro', 'Gamble Feature'],
            ],

            // NoLimit City
            [
                'provider_code' => 'NO_LIMIT',
                'game_code' => 'san-quentin',
                'name' => 'San Quentin xWays',
                'slug' => 'san-quentin-xways',
                'cover_image' => 'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=600&auto=format&fit=crop&q=80',
                'category' => 'buy_feature',
                'is_featured' => true,
                'rtp_display' => '96.03%',
                'volatility' => 'Insane',
                'min_bet' => 0.20,
                'max_bet' => 32.00,
                'max_multiplier' => 150000,
                'play_count' => 1480,
                'tags' => ['xWays', 'xNudge', 'Lockdown Spins'],
            ],
            [
                'provider_code' => 'NO_LIMIT',
                'game_code' => 'mental',
                'name' => 'Mental',
                'slug' => 'mental',
                'cover_image' => 'https://images.unsplash.com/photo-1514533450685-4493e01d1fdc?w=600&auto=format&fit=crop&q=80',
                'category' => 'slots',
                'is_featured' => false,
                'rtp_display' => '96.08%',
                'volatility' => 'Insane',
                'min_bet' => 0.20,
                'max_bet' => 70.00,
                'max_multiplier' => 66666,
                'play_count' => 830,
                'tags' => ['Dark', 'Fire Frames', 'Autopsy'],
            ],

            // Live Dealer / Tables
            [
                'provider_code' => 'EVOLUTION',
                'game_code' => 'lightning-roulette',
                'name' => 'Lightning Roulette',
                'slug' => 'lightning-roulette',
                'cover_image' => 'https://images.unsplash.com/photo-1511193311914-0346f16efe90?w=600&auto=format&fit=crop&q=80',
                'category' => 'live',
                'is_featured' => true,
                'rtp_display' => '97.30%',
                'volatility' => 'High',
                'min_bet' => 0.50,
                'max_bet' => 5000.00,
                'max_multiplier' => 500,
                'play_count' => 1310,
                'tags' => ['Live Host', 'Lucky Numbers', '500x'],
            ],
            [
                'provider_code' => 'EVOLUTION',
                'game_code' => 'crazy-time',
                'name' => 'Crazy Time',
                'slug' => 'crazy-time',
                'cover_image' => 'https://images.unsplash.com/photo-1596838132731-3301c3fd4317?w=600&auto=format&fit=crop&q=80',
                'category' => 'live',
                'is_featured' => true,
                'rtp_display' => '96.08%',
                'volatility' => 'High',
                'min_bet' => 0.10,
                'max_bet' => 2500.00,
                'max_multiplier' => 25000,
                'play_count' => 1650,
                'tags' => ['Game Show', 'Pachinko', 'Coin Flip'],
            ],
        ];

        foreach ($gamesData as $g) {
            Game::updateOrCreate(['slug' => $g['slug']], $g);
        }

        // 4. Populate Live Community Winners Feed (Realistic non-rounded Euro amounts with all tiers)
        $winsData = [
            [
                'player_name' => 'Sven O.',
                'avatar' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
                'game_name' => 'Gates of Olympus 1000',
                'game_code' => 'vs20olympgate',
                'provider_code' => 'PRAGMATIC',
                'bet_amount' => 10.00,
                'win_amount' => 5840.60,
                'multiplier' => 584.06,
                'tier' => 'epic',
            ],
            [
                'player_name' => 'Elena R.',
                'avatar' => 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
                'game_name' => 'Wanted Dead or a Wild',
                'game_code' => 'wanted-dead-or-a-wild',
                'provider_code' => 'HACKSAW',
                'bet_amount' => 5.00,
                'win_amount' => 3127.40,
                'multiplier' => 625.48,
                'tier' => 'mega',
            ],
            [
                'player_name' => 'Dmitri V.',
                'avatar' => 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
                'game_name' => 'Sweet Bonanza 1000',
                'game_code' => 'vs20sweetbonz',
                'provider_code' => 'PRAGMATIC',
                'bet_amount' => 4.00,
                'win_amount' => 1484.60,
                'multiplier' => 371.15,
                'tier' => 'big',
            ],
            [
                'player_name' => 'Lucas M.',
                'avatar' => 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
                'game_name' => 'Mahjong Ways 2',
                'game_code' => 'mahjong-ways-2',
                'provider_code' => 'PGSOFT',
                'bet_amount' => 2.00,
                'win_amount' => 458.20,
                'multiplier' => 229.10,
                'tier' => 'big',
            ],
            [
                'player_name' => 'Katarina S.',
                'avatar' => 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
                'game_name' => 'Crazy Time',
                'game_code' => 'crazy-time',
                'provider_code' => 'EVOLUTION',
                'bet_amount' => 20.00,
                'win_amount' => 8940.25,
                'multiplier' => 447.01,
                'tier' => 'epic',
            ],
            [
                'player_name' => 'Matteo B.',
                'avatar' => 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
                'game_name' => 'San Quentin xWays',
                'game_code' => 'san-quentin-xways',
                'provider_code' => 'NO_LIMIT',
                'bet_amount' => 1.00,
                'win_amount' => 2410.80,
                'multiplier' => 2410.80,
                'tier' => 'mega',
            ],
            [
                'player_name' => 'Sophie L.',
                'avatar' => 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
                'game_name' => 'Sugar Rush 1000',
                'game_code' => 'vs20sugarush',
                'provider_code' => 'PRAGMATIC',
                'bet_amount' => 2.00,
                'win_amount' => 260.40,
                'multiplier' => 130.20,
                'tier' => 'win',
            ],
            [
                'player_name' => 'Oliver P.',
                'avatar' => 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
                'game_name' => 'Shining Crown',
                'game_code' => 'shining-crown',
                'provider_code' => 'AMUSNET',
                'bet_amount' => 5.00,
                'win_amount' => 78.50,
                'multiplier' => 15.70,
                'tier' => 'standard',
            ],
        ];

        foreach ($winsData as $w) {
            LiveCommunityWin::create(array_merge($w, ['is_simulated' => false]));
        }
    }
}
